const order_confirmation = require('./model')
const { successResponses, errorResponses, pagination } = require('../../utils')

module.exports = {
  getAll: async(req, res) => {
    try{
      const order_confirmations = await order_confirmation.findAndCountAll({
        attributes: {
          exclude: ['ordersId'],
        },
        include: 'orders'
      })
      const data = pagination(order_confirmations, {...req.query})
      return successResponses[200](res, {data})
    }catch(err){
      return errorResponses[400](res, {message: err.message})
    }
  },

  create: async(req, res) => {
    try{
      const data = await order_confirmation.create({...req.body})
      return successResponses[201](res,{data})
    }catch(err){
      return errorResponses[400](res, {message: err.message})
    }
  },

  update: async(req, res) => {
    try{
      const data = await order_confirmation.update({...req.body},{
        where: {
          id: req.params.id
        }
      })
      return successResponses[202](res,{data})
    }catch(err){
      return errorResponses[400](res, {message: err.message})
    }
  },

  getById: async(req, res) => {
    try{
      const data = await order_confirmation.findOne({
        where: {
          id: req.params.id
        }
      })
      if(data!=null){
        res.send(successResponses[200](res, {data}))
      }else{
        res.send(errorResponses[400](res, {message: 'id not found'}))
      }
    }catch(err){
      return errorResponses[400](res, {message: err.message})
    }
  },

  delete: async(req, res) => {
    try{
      const cek = await order_confirmation.findOne({
        where: {
          id: req.params.id
        }
      })
      if(cek!=null){
        const data = await order_confirmation.destroy({
          where: {
            id: req.params.id
          }
        })
        res.send(successResponses[200](res, {data}))
      }else{
        res.send(errorResponses[400](res, {message: 'id not found'}))
      }
    }catch(err){
      return errorResponses[400](res, {message:err.message})
    }
  },
}